### ISSUE TITLE
hourglass on app startup

### ISSUE THREAD

**Issue by kajok1979** [wh00hw/Coffee-EEPROM-FAP#1]
Hi, I'm trying the app. it block the FlipperZero (Roguemaster RM1226-1952-0.74.3-499dea0) with an hourglass on app startup.  thanks
Kaj

**Comment by wh00hw** [comment]
Hi, check the correctness of the connections between the EEPROM and the Flipper. I can not reproduce the issue, mine is working correctly on Unleashed (unlshd-022)

**Comment by kajok1979** [comment]
i'm testing with Unleashed (unlshd-022)and your repository "applications_user" directory.
i compile using fbt:

fbt updater_package
        SDKCHK  firmware\targets\f7\api_symbols.csv
←[32mAPI version 11.5 is up to date←[0m
        CDB     build\f7-firmware-D\compile_commands.json
←[32mLinking build\f7-firmware-D as latest built dir (./build/latest/)←[0m
        CC      applications_user\coffee_eeprom_app\coffee_eeprom.c
applications_user\coffee_eeprom_app\coffee_eeprom.c: In function 'coffee_eeprom_app':
applications_user\coffee_eeprom_app\coffee_eeprom.c:78:21: error: enumeration value 'InputKeyMAX' not handled in switch [-Werror=switch]
   78 |                     switch(event.input.key) {
      |                     ^~~~~~
cc1.exe: all warnings being treated as errors
scons: *** [build\f7-firmware-D\.extapps\coffee_eeprom\coffee_eeprom.o] Error 1

********** FBT ERRORS **********
build\f7-firmware-D\.extapps\coffee_eeprom\coffee_eeprom.o: Error 1



or trying with your file.FAP  uploaded directly on sd but on run app show:
error: preload failed API verrsion mismatch.

I'm sorry to disturb you
Kaj

**Comment by wh00hw** [comment]
try now, pull the latest commit and compile with `fbt fap_coffee_eeprom`, you should see the compiled .fap file in `build\f7-firmware-D\.extapps\coffee_eeprom.fap`
