### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by michelinok** [wh00hw/Coffee-EEPROM-FAP#3]
Hi!
When I try to compile the fap I get this error:

applications_user\coffee_eeprom_app\coffee_eeprom.c:11:10: fatal error: lib/toolbox/random_name.h: No such file or directory
   11 | #include <lib/toolbox/random_name.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
scons: *** [build\f7-firmware-C\.extapps\coffee_eeprom\coffee_eeprom.o] Error 1

********** FBT ERRORS **********
build\f7-firmware-C\.extapps\coffee_eeprom\coffee_eeprom.o: Error 1

Any idea?

**Comment by wh00hw** [comment]
Yep. They changed the random names generator library, I've just released the fix, compile it as usual. Thanks for noticing
